export const BigPrimary = "text-[white] bg-[transparent] px-6 py-2 text-xl border-2 h-[50px] leading-xl border-[white] hover:text-[black] hover:bg-[white]"
export const BigSecondary = "text-textsecondary bg-[white] px-6 py-2 text-xl border-[2px] h-[50px] leading-xl border-[white] hover:text-[black]"
export const MidPrimary = "text-[white] bg-[transparent] px-[18px] py-2 text-lg border-[2px] h-10 leading-lg border-[white] hover:text-[black] hover:bg-[white]"
export const MidSecondary = "text-textsecondary bg-[transparent] px-[18px] py-2 text-lg border-[2px] h-10 leading-lg border-textsecondary hover:text-[white] hover:bg-[black]"
export const SmallPrimary = "text-[white] bg-buttonprimary px-[14px] py-[6px] text-sm border-[2px] h-[30px] leading-sm border-buttonprimary hover:bg-buttonsecondary"
export const SmallSecondary = "text-textsecondary bg-[transparent] px-[14px] py-[5px] text-sm border-[2px] h-[30px] leading-sm border-textsecondary hover:text-[white] hover:bg-[black]"